export const Room = {
    MaLichChieu: 750,
    DanhSachGhe: [
      {
        MaGhe: 7081,
        TenGhe: '01',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 1,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7082,
        TenGhe: '02',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 2,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7083,
        TenGhe: '03',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 3,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7084,
        TenGhe: '04',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 4,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7085,
        TenGhe: '05',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 5,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7086,
        TenGhe: '06',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 6,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7087,
        TenGhe: '07',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 7,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7088,
        TenGhe: '08',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 8,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7089,
        TenGhe: '09',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 9,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7090,
        TenGhe: '10',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 10,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7091,
        TenGhe: '11',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 11,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7092,
        TenGhe: '12',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 12,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7093,
        TenGhe: '13',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 13,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7094,
        TenGhe: '14',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 14,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7095,
        TenGhe: '15',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 15,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7096,
        TenGhe: '16',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 16,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7097,
        TenGhe: '17',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 17,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7098,
        TenGhe: '18',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 18,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7099,
        TenGhe: '19',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 19,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7100,
        TenGhe: '20',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 20,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7101,
        TenGhe: '21',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 21,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7102,
        TenGhe: '22',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 22,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7103,
        TenGhe: '23',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 23,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7104,
        TenGhe: '24',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 24,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7105,
        TenGhe: '25',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 25,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7106,
        TenGhe: '26',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 26,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7107,
        TenGhe: '27',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 27,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7108,
        TenGhe: '28',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 28,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7109,
        TenGhe: '29',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 29,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7110,
        TenGhe: '30',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 30,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7111,
        TenGhe: '31',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 31,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7112,
        TenGhe: '32',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 32,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7113,
        TenGhe: '33',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 33,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7114,
        TenGhe: '34',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 34,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7115,
        TenGhe: '35',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 35,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7116,
        TenGhe: '36',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 36,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7117,
        TenGhe: '37',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 37,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7118,
        TenGhe: '38',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 38,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7119,
        TenGhe: '39',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 39,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7120,
        TenGhe: '40',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 40,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7121,
        TenGhe: '41',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 41,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7122,
        TenGhe: '42',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 42,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7123,
        TenGhe: '43',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 43,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7124,
        TenGhe: '44',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 44,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7125,
        TenGhe: '45',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 45,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7126,
        TenGhe: '46',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 46,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7127,
        TenGhe: '47',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 47,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7128,
        TenGhe: '48',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 48,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7129,
        TenGhe: '49',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 49,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7130,
        TenGhe: '50',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 50,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7131,
        TenGhe: '51',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 51,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7132,
        TenGhe: '52',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 52,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7133,
        TenGhe: '53',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 53,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7134,
        TenGhe: '54',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 54,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7135,
        TenGhe: '55',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 55,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7136,
        TenGhe: '56',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 56,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7137,
        TenGhe: '57',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 57,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7138,
        TenGhe: '58',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 58,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7139,
        TenGhe: '59',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 59,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      },
      {
        MaGhe: 7140,
        TenGhe: '60',
        MaRap: 380,
        LoaiGhe: 'Thuong',
        STT: 60,
        GiaVe: 75000,
        DaDat: false,
        MaNhom: 'GP10',
        TaiKhoanNguoiDat: null
      }
    ]
  }